spring:
  application:
    name: ms-auth
  flyway:
    depends-on: entityManagerFactory
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: ms_user
    password: ms123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

server:
  port: 8081

security:
  jwt:
    secret-key: 29e173be957eb2e6981cc208b67247ff8f894a632764f65ede6cba377d534663
    expiration-time: 3600000
    refresh-expiration-time: 604800000
