spring:
  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: >
                StockInsufficientEvent:com.br.kafka.event.StockInsufficientEvent,
                StockReservedEvent:com.br.kafka.event.StockReservedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: ms_user
    password: ms123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

server:
  port: 8082

security:
  jwt:
    public-key: classpath:keys/publicKey.pem
