services:
  postgres:
    image: postgres:15-alpine
    container_name: ms-postgres
    environment:
      POSTGRES_DB: ms
      POSTGRES_USER: ms_user
      POSTGRES_PASSWORD: ms123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: